name: pre-commit

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@main
    - uses: pre-commit/action@v2.0.0
